# Generated by Django 2.1.5 on 2019-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='NA', max_length=50)),
                ('product_desc', models.CharField(default='NA', max_length=300)),
                ('product_seller', models.CharField(default='NA', max_length=100)),
                ('product_stock', models.IntegerField(default=0)),
                ('product_pubdate', models.DateField(default='2019-07-01')),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
