# Generated by Django 2.1.5 on 2019-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cat',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcat',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(default='NA', max_length=1500),
        ),
    ]
