# Generated by Django 2.1.5 on 2019-07-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190702_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amt',
            field=models.IntegerField(default=0),
        ),
    ]
