# Generated by Django 2.1.5 on 2019-07-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phoneno',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
