# Generated by Django 2.1.5 on 2019-07-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_feedback_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phoneno',
            field=models.IntegerField(default=0),
        ),
    ]
